Implement mobile changes
dogecoinfoundation/dogecoin.com pull request #125
Opened 2022-07-21 03:57 UTC by alamshafil

Implement mobile changes based on #124:

Would like feedback on this PR.

**Issue 1.** Edge padding increase in drop-down menu
**Commit:** [Add padding to inner menu for mobile](https://github.com/dogecoinfoundation/dogecoin.com/commit/4d061287419c00ce75f03aa9a9e837fd5695e320)
![Screenshot from 2022-07-20 23-48-32](https://user-images.githubusercontent.com/36016500/180126697-4ce25df3-9642-477b-9113-07296c3e794d.png)

**Issue 2.** Decrease edge padding on Dogepedia page
**Commit:** [ Increase dogepedia box width to 90vw](https://github.com/dogecoinfoundation/dogecoin.com/commit/e9bc73c462cc4c1c43dd4641318dd54d26db505f)
![Screenshot from 2022-07-20 23-49-04](https://user-images.githubusercontent.com/36016500/180126720-65d61681-8b03-4a1b-9bb6-8033c643efea.png)

**Issue 3.** Minor nit: sub-heading font looks out of place and left-margin
**Commit:** [Make dogepedia h3 have 0 left margin](https://github.com/dogecoinfoundation/dogecoin.com/commit/e8fc09be7a16ee89b3939decdb357bf2fbe57608)

**Issue 7.** Dark mode social media has white background
**Commit:** [Remove background and text decoration from social](https://github.com/dogecoinfoundation/dogecoin.com/commit/e4da0400a2382ad600079ec448736c12d1433b3c)
![Screenshot from 2022-07-20 23-49-27](https://user-images.githubusercontent.com/36016500/180126749-79e600ad-39f4-45b8-a1ff-b34c10414cf4.png)

Can squash commits if needed.

2022-07-29 11:03 UTC, xanimo requested changes
First things first please rebase against main to resolve those conflicts in:
themes/hello-friend-ng/assets/scss/_dogepedia.scss
themes/hello-friend-ng/layouts/partials/community.html 

These look sensible though and will ACK upon conflict resolution after a test build locally tomorrow.

2022-07-30 21:37 UTC, alamshafil commented
I have rebased against the main branch.

2022-08-01 21:35 UTC, xanimo reviewed
Apologies for the delay! I've just tested on emulated Samsung Galaxy S20 (360 x 800) and your changes are looking good! I did however notice a couple things that I'm not sure if you'd like to tackle or if we should split and make new issues for, but I figured I'd ask you here since this PR's focus is on UI/UX. They are:

![image](https://user-images.githubusercontent.com/31856436/182249868-ebcab795-f14f-4d51-9cba-e4774573710c.png)
On page load on the landing when the navbar is expanded we're still getting those funky styles on the translation dropdown.

![Screenshot from 2022-08-01 14-24-12](https://user-images.githubusercontent.com/31856436/182249643-db107d6c-f730-4f53-9fd9-06442a340bb5.png)
The headers above need a tad bit of padding in extra small media queries and:

![Screenshot from 2022-08-01 14-24-45](https://user-images.githubusercontent.com/31856436/182250029-9dfdd2f4-c1ac-4483-8e2a-1b1d7096a18d.png)

In dark mode, considering the reddit icon's text is dark on dark perhaps we should just make that particular section a bit lighter for legibility purposes?

Let me know what you're thinking and if you'd like to fix, otherwise will ACK what you already have and we can add new issues for it. 

Thanks!

2022-08-02 20:09 UTC, alamshafil commented
Sorry for late response, I believe I can fix these in separate issues. I talked to @qlpqlp about the second screenshot and he said we would fix it and there was some bug on the emulator which caused that. I feel like it's better to make separate issue/PRs to make it more clear what's being changed/added.

Thanks for reviewing!

2022-08-03 08:12 UTC, xanimo approved these changes

2022-08-03 08:14 UTC, xanimo commented
> Sorry for late response, I believe I can fix these in separate issues. I talked to @qlpqlp about the second screenshot and he said we would fix it and there was some bug on the emulator which caused that. I feel like it's better to make separate issue/PRs to make it more clear what's being changed/added.
> 
> Thanks for reviewing!

ACK. Sounds good to me!

2022-08-03 19:09 UTC, qlpqlp commented
Will merge this now to continue to apply + improvements :)

2022-08-03 19:09 UTC, merged