translate who-owns-dogecoin.md into Chinese
dogecoinfoundation/dogecoin.com pull request #172
Opened 2022-08-11 11:17 UTC by shuferhoo

translate who-owns-dogecoin.md into Chinese

2022-08-11 11:26 UTC, shuferhoo commented
@bobdos

2022-08-11 12:55 UTC, bobdos requested changes

2022-08-11 12:55 UTC, bobdos commented on content/zh-cn/dogepedia/articles/who-owns-dogecoin.md
> +狗狗币的一大优点是没有个人或公司团体能够控制狗狗币区块链网络：它是完全开源的、无需许可的、去中心化的和点对点的。
原文是 "owns"，所以这句翻译里面的“控制”，请翻译为“拥有”

2022-08-11 12:55 UTC, bobdos commented on content/zh-cn/dogepedia/articles/who-owns-dogecoin.md
> +狗狗币节点通过去中心化的共识机制，来防止恶意参与者获得对狗狗币网络的控制权。简单的来说，当且仅有狗狗币区块链上超过一半的节点认同一笔交易有效，那么这笔交易就会被处理并记录到区块链中。
“那么这笔交易就会被处理并记录到区块链中”，建议调整为“那么这笔交易才会被处理并记录到区块链中” （把“就”调整为“才”）

2022-08-12 00:25 UTC, bobdos approved these changes
all good and it's ready to go!

many thanks for your contribution.

cheers,

2022-08-12 00:25 UTC, merged