translate get-dogecoin.md into Chinese
dogecoinfoundation/dogecoin.com pull request #173
Opened 2022-08-12 11:00 UTC by shuferhoo

translate get-dogecoin.md into Chinese

2022-08-12 11:19 UTC, bobdos commented
hi @shuferhoo 

do you have a dogecoin wallet? 

then I can donate some to you to say thank you for your contribution, personally.

2022-08-12 12:13 UTC, shuferhoo commented
> hi @shuferhoo
> 
> do you have a dogecoin wallet?
> 
> then I can donate some to you to say thank you for your contribution, personally.



> hi @shuferhoo
> 
> do you have a dogecoin wallet?
> 
> then I can donate some to you to say thank you for your contribution, personally.

thank you, i have a wallet DKZU4AYzvbR8W9MSUrUG8ACsdjMo1U3tkB. I am happy to be a dogecoin contributor.

2022-08-12 13:02 UTC, bobdos commented
> 

cool, just donate Ð420 to you:

https://blockchair.com/dogecoin/address/DKZU4AYzvbR8W9MSUrUG8ACsdjMo1U3tkB

cheers,

2022-08-12 13:18 UTC, shuferhoo commented
@bobdos i have received it,  thank you so much as it is my first being tipping!
Please merge my pull request，i am very looking forward to it，hahahah

2022-08-13 11:36 UTC, bobdos requested changes

2022-08-13 11:36 UTC, bobdos commented on content/zh-cn/dogepedia/articles/get-dogecoin.md
> +你可以在交易所按照当前市场价格购买狗狗币，这被称为现价交易。或者你可以出一个价格，当市场价格到达这个价格的时候就会达成交易，这被称为限价交易。有一些交易所只允许他们的用户进行市价交易。
"你可以在交易所按照当前市场价格购买狗狗币，这被称为现价交易" 中 ”现价“调整为”市价“，这样和段落结尾的”市价交易“的翻译保持一致性。

2022-08-13 11:36 UTC, bobdos commented on content/zh-cn/dogepedia/articles/get-dogecoin.md
> +尽管现在交易所的安全性已经有了很大提升，但是你在通过交易所购买狗狗币钱还是需要自己进行仔细的研究，一些风险和争议性问题仍然有可能出现。更安全起见，最好还是考虑把你的短期不打算用于交易的狗狗币放到一个[私有非托管钱包](/zh-cn/dogepedia/articles/how-do-i-get-a-wallet)里。
”自己进行仔细的研究“ 需要和原文**do your own research (DYOR)**一样保持粗体状态

2022-08-13 11:36 UTC, bobdos commented on content/zh-cn/dogepedia/articles/get-dogecoin.md
> +这里还有很多方法可以获得狗狗币。一些活动比如[Dogecoin Folding @ Home](/zh-cn/dogepedia/articles/dogecoin-folding-at-home),包括[挖矿](/zh-cn/dogepedia/how-tos/mining-dogecoin)都可以获得一些狗狗币!
本段落中的英文逗号"," 需要 转换为 中文逗号"，"

2022-08-13 12:30 UTC, shuferhoo commented
@bobdos ok, i have changed all these requests.

2022-08-13 13:40 UTC, bobdos approved these changes
all good and it's ready to go.

many thanks for your contribution.

cheers.

2022-08-13 13:40 UTC, merged