translate dogecoin-has-no-utility.md into Chinese
dogecoinfoundation/dogecoin.com pull request #180
Opened 2022-08-19 11:48 UTC by randomwalk266

@bobdos

2022-08-21 12:04 UTC, LuminescenceRecordings approved these changes

2022-08-22 12:18 UTC, bobdos requested changes

2022-08-22 12:18 UTC, bobdos commented on content/zh-cn/dogepedia/faq/dogecoin-has-no-developers.md
> +从2015年的狗狗币1.10.0开始，狗狗币开发团队决定从比特币中重新分叉出狗狗币，在比特币的代码库之上重新实现莱特币的一些更改。因此，从历史上看，狗狗币继承自比特币功能完整的代码库，共享了比特币的很多优良性质。它的一些独性主要来自于参数更改、功能优化以及一些不是继承自莱特币和比特币继承的代码。这些更改都是致力于使狗狗币成为方便日常使用的可用货币，注重实用性和易用性。
1. 它的一些独性主要来自于参数更改->它的一些独特性主要来自于参数更改
2. 以及一些不是继承自莱特币和比特币继承的代码->以及一些不是继承自莱特币和比特币的代码

2022-08-22 12:18 UTC, bobdos commented on content/zh-cn/dogepedia/faq/dogecoin-has-no-developers.md
> +狗狗币基金会[路线图](https://foundation.dogecoin.com/trailmap/)列出了一些项目，通过这些项目，狗狗币生态社区将会朝着狗狗币的目标进发，一切为了人民，一切也都依靠人民！这个路线图不是强制的，但是指明了一个方向，社区可以朝着这个方向来做反馈，来提建议。
1. https://foundation.dogecoin.com/trailmap/  -> https://foundation.dogecoin.com/zh-cn/trailmap/
2. 这个路线图不是强制的，但是指明了一个方向，社区可以朝着这个方向来做反馈，来提建议 -> 这个路线图不是强制的，而是供社区公开讨论，并根据社区反馈来调整前进方向。

2022-08-22 12:18 UTC, bobdos commented on content/zh-cn/dogepedia/faq/dogecoin-has-no-utility.md
> +经过多年发展，使用狗狗币在网上商店消费已经成为可能。过去两年，随着狗狗币支付集成到第三方支付比如BitPay、Coinbase及一些支持狗狗币的预付卡提供商，狗狗币的使用呈爆发态势。商店还可以通过JSON-RPC接口直接集成到狗狗币区块链上。狗狗币基金会正在同开发者一起，计划通过创建一些标准化、流程化的软件包，来使得狗狗币支付更便捷。
1. 使用狗狗币在网上商店消费已经成为可能 -> 使用狗狗币在网上商店进行消费已经成为可能

2022-08-22 12:18 UTC, bobdos commented on content/zh-cn/dogepedia/faq/dogecoin-has-no-utility.md
> +根据[狗狗币宣言](https://foundation.dogecoin.com/manifesto/)，狗狗币着重于实用、友善、温暖、值得信赖，同时要保持其独特的快乐文化。
1. https://foundation.dogecoin.com/manifesto/ -> https://foundation.dogecoin.com/zh-cn/manifesto/
2. 狗狗币着重于实用、友善、温暖、值得信赖，同时要保持其独特的快乐文化。-> 狗狗币在秉承实用原则、友好原则、开放原则、以及稳健原则的同时，同时要保持其独特的快乐文化。

2022-08-22 13:10 UTC, bobdos requested changes

2022-08-22 13:10 UTC, bobdos commented on content/zh-cn/dogepedia/faq/dogecoin-has-no-utility.md
> +根据[狗狗币宣言](https://foundation.dogecoin.com/zh-cn/manifesto/)，狗狗币秉承实用原则、友好原则、开放原则以及稳健原则，同时要保持独特的快乐文化。。
。。-> 。（两个句号）

2022-08-22 13:13 UTC, bobdos approved these changes
all good and it's ready to go.

cheers.

2022-08-22 13:13 UTC, merged