Trans cn: becoming-a-dogecoin-developer.md
dogecoinfoundation/dogecoin.com pull request #182
Opened 2022-08-21 11:54 UTC by LuminescenceRecordings

Discord: LRecords#3442

2022-08-21 13:00 UTC, randomwalk266 requested changes
thanks for your contribution. i have translated some article,  such as faqs and how-do-i-get-a-wallet. in order to avoid repetitive work, you can translate other article first.

2022-08-21 13:31 UTC, LuminescenceRecordings commented
> thanks for your contribution. i have translated some article, such as faqs and how-do-i-get-a-wallet. in order to avoid repetitive work, you can translate other article first.

Got it, I do the rest of articles/

2022-08-21 13:47 UTC, randomwalk266 approved these changes

2022-08-21 21:06 UTC, LuminescenceRecordings commented
2 titles of up level mistake,
'使用狗狗币时候我的隐私有保护吗？'   remove   '侯'
'那些慈善机构接受狗狗币？'   change '那' to '哪'
<img width="674" alt="截屏2022-08-22 04 59 40" src="https://user-images.githubusercontent.com/67324650/185810946-93830aeb-2df4-4a69-a933-58713b613397.png">

2022-08-23 12:02 UTC, bobdos requested changes

2022-08-23 12:02 UTC, bobdos commented on content/zh-cn/dogepedia/articles/dogecoin-developers.md
> +整个生态系统的发展也至关重要——就好像参考实现的目的是为了建立一个坚实而稳定的基础，创新可以通过建立在其上的服务产生(有时，与之协同)。有许多独立开发者、组织和公司在现有Dogecoin Core的代码基础上构建服务，包括支付通道功能、对NFT的实验性支持和打赏服务。狗狗币基金会的项目可以在Github上找到，[这里](https://github.com/dogecoinfoundation)
1. Dogecoin Core -> 狗狗币核心
2. [这里] -> [请查看这里]

2022-08-23 12:02 UTC, bobdos commented on content/zh-cn/dogepedia/articles/dogecoin-developers.md
> +你不需要任何授权或许可就可以开始为Dogecoin Core做出贡献或在其上构建新的服务。如果你有兴趣成为一名狗狗币开发者，[在这里](/dogepedia/articles/becoming-a-dogecoin-developer)了解更多。
1. Dogecoin Core -> 狗狗币核心
2. /dogepedia/articles/becoming-a-dogecoin-developer ->/zh-cn/dogepedia/articles/becoming-a-dogecoin-developer/
3. 了解更多 -> 可以了解更多

2022-08-23 13:59 UTC, LuminescenceRecordings commented
@bobdos Nice check, well done

2022-08-24 04:28 UTC, bobdos approved these changes
all good and it's ready to go.

many thanks for your contribution.

this is the way.

cheers.

2022-08-24 04:46 UTC, merged