translate 2 articles into Chinese
dogecoinfoundation/dogecoin.com pull request #187
Opened 2022-08-26 12:30 UTC by randomwalk266

2022-08-27 12:14 UTC, randomwalk266 commented
@bobdos

2022-08-29 11:13 UTC, bobdos commented
will check asap.

2022-08-30 11:03 UTC, bobdos requested changes

2022-08-30 11:03 UTC, bobdos commented on i18n/zh-cn.toml
>  other = "Dogecoin Core"
Dogecoin Core -> 狗狗币核心

2022-08-30 11:03 UTC, bobdos commented on i18n/zh-cn.toml
> +other = "Dogecoin Core是一个完整的钱包，它通过下载完整的区块链数据来进行同步，提供了一个独立运行的狗狗币钱包。"
Dogecoin Core -> 狗狗币核心

2022-08-30 11:03 UTC, bobdos commented on i18n/zh-cn.toml
> +other = "博文"
博文 -> 博客

2022-08-30 11:03 UTC, bobdos commented on i18n/zh-cn.toml
> +other = "随时了解基金会开发者们的博文！"
博文 -> 博客

2022-08-30 11:36 UTC, randomwalk266 commented
@bobdos

2022-08-30 14:02 UTC, bobdos approved these changes
all good and it's ready to go!

many thanks.

2022-08-30 14:02 UTC, merged