CN trans
dogecoinfoundation/dogecoin.com pull request #188
Opened 2022-08-27 02:10 UTC by LuminescenceRecordings

2022-08-29 11:13 UTC, bobdos commented
will check asap.

2022-08-30 11:19 UTC, bobdos requested changes

2022-08-30 11:19 UTC, bobdos commented on content/zh-cn/dogepedia/articles/dogecoin-hardware-wallets.md
> +通常，硬件钱包可以通过USB或蓝牙等其他设备连接到电脑。通过此连接，它们可以用来给在外部设备(如你的电脑)上运行的钱包应用程序中发生的交易签名。交易是在硬件钱包内进行签名的，除非硬件钱包以前有被泄露过，否则在整个过程中私钥永远不会向外界公开。
它们可以用来给在外部设备(如你的电脑)上运行的钱包应用程序中发生的交易签名 -> 它们可以用来对外部设备(如你的电脑)上运行的钱包应用程序中的交易进行签名

2022-08-30 11:19 UTC, bobdos commented on content/zh-cn/dogepedia/articles/dogecoin-hardware-wallets.md
> +如今，大多数硬件钱包都依赖于使用*助记词*，助记词作为一种管理钥匙通常是由24个单词组成，硬件钱包通过使用它来计算出私钥来访问和使用你所持有的加密货币。在首次使用硬件钱包时，可以输入新的助记词或者旧的助记词。
管理钥匙 -> 主密钥

硬件钱包通过使用它来计算出私钥来访问和使用你所持有的加密货币 -> 硬件钱包通过使用它计算出私钥并访问和使用你所持有的加密货币

可以输入新的助记词或者旧的助记词 -> 可以生成新的助记词或者输入旧的助记词

2022-08-30 11:19 UTC, bobdos commented on content/zh-cn/dogepedia/articles/dogecoin-hardware-wallets.md
> +助记词是你在硬件钱包中所有加密货币的钥匙。正因如此，它也被称为*恢复短语*，你必须在几个安全的地方，将它储存在多个副本中。助记词的副本就等于你对你的硬件钱包进行了完整的备份，即使你的硬件钱包丢失了，你也可以通过简单地输入你曾备份的助记词到新钱包中，从而来恢复你所有的加密货币。
你必须在几个安全的地方，将它储存在多个副本中 -> 你必须在数个安全的地方，并将它储存在多个副本中

助记词的副本就等于你对你的硬件钱包进行了完整的备份 -> 助记词的副本就等同于你对自己的硬件钱包进行了完整备份

从而来恢复你所有的加密货币 -> 从而恢复你所有的加密货币

2022-08-30 11:19 UTC, bobdos commented on content/zh-cn/dogepedia/articles/dogecoin-hardware-wallets.md
> +使用狗狗币的硬件钱包非常容易，所有的硬件钱包制造商都提供了说明，来指导你如何使用他们的设备进行交易。通常情况下，只需将设备插入电脑，输入PIN或可选的密码，然后开始并确认你想要进行的交易。硬件钱包的另一个好处是，它们可以使你的狗狗币交易变得更加容易以保护你的隐私。
它们可以使你的狗狗币交易变得更加容易的同时亦保护你的[隐私](/zh-cn/dogepedia/articles/dogecoin-and-privacy)

2022-08-30 11:19 UTC, bobdos commented on content/zh-cn/dogepedia/articles/dogecoin-hardware-wallets.md
> +从理论上讲，这使得硬件钱包在有风险的电脑上使用也很安全。有几家硬件钱包制造商，它们在其硬件和相关软件中都包含了不同的特性，以防止加密货币持有者在存储加密货币时落入常见的陷阱。这些特性可能包括安全pin、自毁机制和自动生成助记词。
pin -> PIN码

2022-08-30 22:52 UTC, LuminescenceRecordings commented
Edited, nice check @bobdos

2022-08-31 00:07 UTC, bobdos approved these changes
all good and it's ready to go.

cheers.

2022-08-31 00:08 UTC, merged