First Draft of 'Who Owns and Controls Dogecoin' Article
dogecoinfoundation/dogecoin.com pull request #21
Opened 2021-12-20 03:06 UTC by RichieJohn

Please check whether links point to valid URL.

2021-12-21 03:01 UTC, MishaBoar requested changes

2021-12-21 03:01 UTC, MishaBoar commented on content/dogepedia/articles/who-owns-dogecoin.md
> +The Dogecoin network is “controlled” by the network of nodes through which it operates. Anyone can run a node, and to learn how to do so, [click here](https://dogecoin.com/dogepedia/how-tos/operating
```suggestion
The Dogecoin network is “controlled” by the network of nodes through which it operates. Anyone can run a node, and to learn how to do so, [click here](/dogepedia/how-tos/operating-a-node). Some nodes also [mine Dogecoin](/dogepedia/how-tos/mining-dogecoin), meaning they perform computational work as part of the process to both confirm all transactions up to the next block, and the next block. They are rewarded for this work with a block reward. 
```

2021-12-21 03:01 UTC, MishaBoar commented on content/dogepedia/articles/who-owns-dogecoin.md
> +The Dogecoin network is “controlled” by the network of nodes through which it operates. Anyone can run a node, and to learn how to do so, [click here](https://dogecoin.com/dogepedia/how-tos/operating
Relative paths. Links are fine!

2021-12-21 03:53 UTC, RichieJohn reviewed
Great - will use relative paths in future articles. :)

2021-12-22 00:42 UTC, RichieJohn commented
This hasn't been merged yet. Owing to my newbie GitHub status, wondering whether I've done something incorrectly? Apologies if so! @tjstebbing @MishaBoar

2021-12-27 04:58 UTC, MishaBoar approved these changes

2021-12-27 04:59 UTC, merged