translate what-is-a-mining-pool.md into Chinese
dogecoinfoundation/dogecoin.com pull request #232
Opened 2022-10-05 14:28 UTC by randomwalk266

2022-10-05 14:28 UTC, randomwalk266 commented
@bobdos

2022-10-06 09:59 UTC, bobdos commented
will check asap. many thanks.

2022-10-07 05:22 UTC, bobdos requested changes

2022-10-07 05:22 UTC, bobdos commented on content/zh-cn/dogepedia/articles/what-is-a-mining-pool.md
> +**挖矿奖励** - 每个区块10,000枚狗狗币再加上区块相关的交易费奖励 - 将给予网络上在其他矿工之前发现新区块有效工作量证明的矿工。然而，单一矿工拥有的哈希算力，跟整个网络的**挖矿哈希算力**比，实在是太小了。这意味着一个旷工，即使使用一个强有力的[**ASIC矿机**](/zh-cn/dogepedia/how-tos/mining-dogecoin/#ASICs)，获得下一个区块奖
这意味着一个旷工->这意味着一个矿工

2022-10-07 05:22 UTC, bobdos commented on content/zh-cn/dogepedia/articles/what-is-a-mining-pool.md
> +通过在矿池中与其他矿工一起努力，以此协调大家的工作并按照事先同意的规则来进行分配奖励，矿工可以获得更稳定的狗狗币奖励。尽管每矿工只获得全部区块奖励的一部分，但是拉长来看，参与到矿池中挖矿可以获得更加可预测及更多的狗狗币奖励。
以此协调大家的工作并按照事先同意的规则来进行分配奖励->以此协调大家的工作并按照事先同意的规则来分配奖励

尽管每矿工只获得全部区块奖励的一部分->尽管每个矿工只获得全部区块奖励的一部分

但是拉长来看->但是长远来看

2022-10-07 05:22 UTC, bobdos commented on content/zh-cn/dogepedia/articles/what-is-a-mining-pool.md
> +开发人员，节点运营商和狗狗币用户是对网络施加影响的其他力量，并且通常应该平衡并控制矿池和矿工的影响。单个矿工也可以选择在较小的矿池中开采，而不是加入最大和最受欢迎的矿池。
这句翻译重复了，并且缺失url，可以删除掉。

2022-10-07 05:22 UTC, bobdos commented on content/zh-cn/dogepedia/articles/what-is-a-mining-pool.md
> +矿池贡献了狗狗币网络的绝大部分哈希算力，在狗狗币这样的工作量证明加密货币发挥了重要的基础性作用，所以他们拥有相当大的权力和影响力。
在狗狗币这样的工作量证明加密货币发挥了重要的基础性作用->在狗狗币这样的工作量证明加密货币(的正常运行中)发挥了重要的基础性作用

2022-10-07 09:16 UTC, randomwalk266 commented
@bobdos

2022-10-07 09:43 UTC, bobdos approved these changes
all good and it's ready to go.

many thanks!

2022-10-07 09:44 UTC, merged