Translation of zh-tw - part of Dogepedia
dogecoinfoundation/dogecoin.com pull request #236
Opened 2022-10-11 11:23 UTC by ukewea

Fix Dogepedia article links in the following files:
- content/zh-tw/dogepedia.md
- content/zh-tw/dogepedia/_index.md

Translate following files:
- content/zh-tw/dogepedia/faq/dogecoin-and-coin-burning.md
- content/zh-tw/dogepedia/faq/dogecoin-has-no-developers.md
- content/zh-tw/dogepedia/faq/dogecoin-has-no-utility.md

Please report any issue if found, thanks!

2022-10-17 15:59 UTC, memetaverse commented on content/zh-tw/dogepedia/faq/dogecoin-has-no-developers.md
> +狗狗幣的主要用途一直是被當作貨幣使用。狗狗幣最初是一種名為 Luckycoin 的加密貨幣（自身就是萊特幣的分叉）的分叉。Dogecoin Core 在一開始就只有 Billy Markus（狗狗幣的共同創造者）與 Jackson Palmer 2 位開發人員。2014 年，Billy 和 Jackson 離開了狗狗幣開發工作，接著一個新的開發團隊建立了起來。多年來，狗狗幣開發團隊由一小群維護人
`Dogecoin Core 在一開始就只有 Billy Markus 與 Jackson Palmer 2 位開發人員`
原文我讀起來感覺是 最初釋出第一版時還只有一人在做開發工作，然後查了一下，看到[這篇](https://dogecoin.com/dogepedia/articles/history-of-dogecoin/) 說：Jackson created the Dogecoin.com website and would have been, for a while, the public face of Dogecoin, while Billy worked as a solo developer on the first 4 releases.
因此在想如果這裡改為 `在第一版 Dogecoin Core 釋出時，開發人員只有 Billy Markus （他和 Jackson Palmer 同為狗狗幣創辦人）` 是否更準確~

2022-10-17 16:02 UTC, memetaverse commented on content/zh-tw/dogepedia/faq/dogecoin-has-no-developers.md
> +狗狗幣基金會的[路線圖](https://foundation.dogecoin.com/trailmap/)列出了各種專案，因為這個生態系正在努力實現其共同目標，即由「人民」使其成為人民的貨幣！此路線圖並不權威，只是指明了前進的方向，而且也歡迎社區的反饋。
There is zh-tw translated Trailmap🙂
https://foundation.dogecoin.com/zh-tw/trailmap/

2022-10-17 16:08 UTC, memetaverse commented on content/zh-tw/dogepedia/faq/dogecoin-has-no-developers.md
> +狗狗幣基金會的[路線圖](https://foundation.dogecoin.com/trailmap/)列出了各種專案，因為這個生態系正在努力實現其共同目標，即由「人民」使其成為人民的貨幣！此路線圖並不權威，只是指明了前進的方向，而且也歡迎社區的反饋。
I think that `社群` is more commonly used than `社區` between zh-tw users. Couldn't find a source on this though.😆 What do you think?

2022-10-17 16:13 UTC, memetaverse commented on content/zh-tw/dogepedia/faq/dogecoin-has-no-utility.md
> +狗狗幣在起初只是個玩笑 - 它在過去很好地遵循了這個傳統，在未來也會繼續。它幾乎是從一開始就被當作一種給小費的途徑，以及鼓勵人們做一些有意義的事情：贊助牙買加雪橇隊參加冬奧會、建造肯亞水井、建造狗狗幣汽車以及許多狗狗幣社區支持的瘋狂提案。狗狗幣始終保持了它誕生之初的用途 - 作為一種打賞貨幣，因爲相較於同期的其他貨幣，狗狗幣區塊鏈的交易費用低廉，且交易速度快速。
我想 `the Dogecoin car` 指的是那輛有名的[狗狗賽車](https://www.bnext.com.tw/article/62762/dogecoin-founder?)，你覺得要不要寫出是狗狗幣賽車呢?~

2022-10-17 16:16 UTC, memetaverse commented on content/zh-tw/dogepedia/faq/dogecoin-has-no-utility.md
> +根據[狗狗幣宣言](https://foundation.dogecoin.com/zh-tw/manifesto/)，狗狗幣專注於實用、風度翩翩、好客以及穩健，同時要保持其獨特的趣味感。
個人覺得在這個地方，`熱情友好`或是`開放` 好像比`好客`容易融入語境/理解，你覺得呢?

2022-10-18 03:09 UTC, ukewea commented on content/zh-tw/dogepedia/faq/dogecoin-has-no-developers.md
> +狗狗幣基金會的[路線圖](https://foundation.dogecoin.com/trailmap/)列出了各種專案，因為這個生態系正在努力實現其共同目標，即由「人民」使其成為人民的貨幣！此路線圖並不權威，只是指明了前進的方向，而且也歡迎社區的反饋。
OK, I'll update the URL, and change the translation of 'trailmap' from '路線圖' to '發展路線圖'

2022-10-18 03:10 UTC, ukewea commented on content/zh-tw/dogepedia/faq/dogecoin-has-no-developers.md
> +狗狗幣的主要用途一直是被當作貨幣使用。狗狗幣最初是一種名為 Luckycoin 的加密貨幣（自身就是萊特幣的分叉）的分叉。Dogecoin Core 在一開始就只有 Billy Markus（狗狗幣的共同創造者）與 Jackson Palmer 2 位開發人員。2014 年，Billy 和 Jackson 離開了狗狗幣開發工作，接著一個新的開發團隊建立了起來。多年來，狗狗幣開發團隊由一小群維護人
You are right, I misinterpret the sentence😭...

2022-10-18 03:12 UTC, ukewea commented on content/zh-tw/dogepedia/faq/dogecoin-has-no-developers.md
> +狗狗幣基金會的[路線圖](https://foundation.dogecoin.com/trailmap/)列出了各種專案，因為這個生態系正在努力實現其共同目標，即由「人民」使其成為人民的貨幣！此路線圖並不權威，只是指明了前進的方向，而且也歡迎社區的反饋。
Sure, I'll change translation of 'community' to '社群'

2022-10-18 03:19 UTC, ukewea commented on content/zh-tw/dogepedia/faq/dogecoin-has-no-utility.md
> +根據[狗狗幣宣言](https://foundation.dogecoin.com/zh-tw/manifesto/)，狗狗幣專注於實用、風度翩翩、好客以及穩健，同時要保持其獨特的趣味感。
The meaning of 'welcoming': friendly or making you feel welcome.
I'll change the translation of the word to '熱情友好'.

2022-10-18 03:33 UTC, ukewea commented on content/zh-tw/dogepedia/faq/dogecoin-has-no-utility.md
> +狗狗幣在起初只是個玩笑 - 它在過去很好地遵循了這個傳統，在未來也會繼續。它幾乎是從一開始就被當作一種給小費的途徑，以及鼓勵人們做一些有意義的事情：贊助牙買加雪橇隊參加冬奧會、建造肯亞水井、建造狗狗幣汽車以及許多狗狗幣社區支持的瘋狂提案。狗狗幣始終保持了它誕生之初的用途 - 作為一種打賞貨幣，因爲相較於同期的其他貨幣，狗狗幣區塊鏈的交易費用低廉，且交易速度快速。
OK, I'll change it.

2022-10-18 03:40 UTC, ukewea commented
Thanks for the corrections @memetaverse!
I've update the .md files mentioned, please take a look.

2022-10-18 16:34 UTC, memetaverse commented on content/zh-tw/dogepedia/faq/dogecoin-has-no-utility.md
> +根據[狗狗幣宣言](https://foundation.dogecoin.com/zh-tw/manifesto/)，狗狗幣專注於實用、風度翩翩、好客以及穩健，同時要保持其獨特的趣味感。
'熱情友好' sounds great!

2022-10-18 16:40 UTC, memetaverse requested changes
Thanks for the great work!💛 I added the last comment, please take a look. And we're good to go.

2022-10-18 16:40 UTC, memetaverse commented on content/zh-tw/dogepedia/faq/dogecoin-has-no-utility.md
> +狗狗幣在起初只是個玩笑 - 它在過去很好地遵循了這個傳統，在未來也會繼續。它幾乎是從一開始就被當作一種給小費的途徑，以及鼓勵人們做一些有意義的事情：贊助牙買加雪橇隊參加冬奧會、建造肯亞水井、建造狗狗賽車以及許多狗狗幣社區支持的瘋狂提案。狗狗幣始終保持了它誕生之初的用途 - 作為一種打賞貨幣，因爲相較於同期的其他貨幣，狗狗幣區塊鏈的交易費用低廉，且交易速度快速。
We just need to change '社區' in this sentence to '社群' then you can merge! 😄

2022-10-18 23:41 UTC, ukewea commented on content/zh-tw/dogepedia/faq/dogecoin-has-no-utility.md
> +狗狗幣在起初只是個玩笑 - 它在過去很好地遵循了這個傳統，在未來也會繼續。它幾乎是從一開始就被當作一種給小費的途徑，以及鼓勵人們做一些有意義的事情：贊助牙買加雪橇隊參加冬奧會、建造肯亞水井、建造狗狗賽車以及許多狗狗幣社區支持的瘋狂提案。狗狗幣始終保持了它誕生之初的用途 - 作為一種打賞貨幣，因爲相較於同期的其他貨幣，狗狗幣區塊鏈的交易費用低廉，且交易速度快速。
OK, I've changed the word, please review for the last time (I hope)🙌.

2022-10-19 00:44 UTC, memetaverse approved these changes
Thank you! I've checked them again. All good, please merge! 😄🎉

2022-10-19 01:47 UTC, closed without merging