'Send & Receive Dogecoin' Article
dogecoinfoundation/dogecoin.com pull request #25
Opened 2021-12-20 07:43 UTC by RichieJohn

Please ensure that the link is to a valid URL.

2021-12-21 04:42 UTC, MishaBoar requested changes
All great, just a couple of minor changes I suggested.

2021-12-21 04:42 UTC, MishaBoar commented on content/dogepedia/articles/send-and-receive-dogecoin.md
> +Sending and receiving Dogecoin is very easy to do. Whether you intend to send or receive Dogecoin, in both cases you will need a [wallet](https://dogecoin.com/dogepedia/articles/how-do-i-get-a-wallet
```suggestion
Sending and receiving Dogecoin is very easy to do. Whether you intend to send or receive Dogecoin, in both cases you will need a [wallet](/dogepedia/articles/how-do-i-get-a-wallet).

```

2021-12-21 04:42 UTC, MishaBoar commented on content/dogepedia/articles/send-and-receive-dogecoin.md
> +Sending and receiving Dogecoin is very easy to do. Whether you intend to send or receive Dogecoin, in both cases you will need a [wallet](https://dogecoin.com/dogepedia/articles/how-do-i-get-a-wallet
Relative path

2021-12-21 04:42 UTC, MishaBoar commented on content/dogepedia/articles/send-and-receive-dogecoin.md
> +One of the (many) great things about Dogecoin is that the transaction speed is significantly quicker than other cryptocurrencies – so you won't have long to wait until the transfer is confirmed. The
```suggestion
One of the (many) great things about Dogecoin is that the transaction speed is significantly quicker than other cryptocurrencies – so you won't have long to wait until the transfer is confirmed. The fees to transfer are also extremely low in comparison with other cryptocurrencies. So, what are you waiting for? Send someone some Doge!
```

2021-12-22 06:03 UTC, RichieJohn reviewed
This all looks good to me. Is there anything else I need to do, @tjstebbing or @MishaBoar for this to be merged?

2021-12-27 05:02 UTC, MishaBoar approved these changes

2021-12-27 05:02 UTC, merged