'What is a Blockchain' Article
dogecoinfoundation/dogecoin.com pull request #29
Opened 2021-12-21 05:24 UTC by RichieJohn

2021-12-21 17:12 UTC, MishaBoar requested changes
I proposed some changes to add the concept of miners, clarify how blocks are chained, and some details about why attacks to the network are unlikely.

I would love if some of the Core devs could review this article. Even though it is very ELI5, we must make sure the condensed information is still "overall" correct.

2021-12-21 17:12 UTC, MishaBoar commented on content/dogepedia/articles/what-is-a-blockchain.md
> +In addition to being peer-to-peer and decentralised, another benefit of blockchain technology is that is extremely difficult — and often impossible — to hack, alter, or deceive the system.
I am not sure if this is too detailed for the level of depth we want to get to with these articles. Also, I would like @michilumin and the others to take a look at this before we push it live. Simple does not mean it has to be conceptually misleading.

2021-12-21 19:34 UTC, rnicoll commented on content/dogepedia/articles/what-is-a-blockchain.md
> +When a Dogecoin transaction is made, the information regarding the transaction is stored in what is a called a **block**, which is then distributed to the other nodes throughout the block**chain**. E
Can we avoid the timestamp reference? Miners give it a timestamp according to their own clock, and the network then goes "Eh, close enough" (or not), so it's definitely not an exact timestamp.

Actually I think the original text is closer, but let me give it a go:

"Every block that is created contains the hash of the preceding block, which in turn contains the hash of its preceding block, so on and so forth creating a chain all the way back to Dogecoin’s genesis block."

Notably the blockchain goes backwards only, and finding the next block is something a node handles as part of its implementation detail.

2021-12-21 19:35 UTC, rnicoll commented on content/dogepedia/articles/what-is-a-blockchain.md
> +In addition to being peer-to-peer and decentralised, another benefit of blockchain technology is that is extremely difficult — and often impossible — to hack, alter, or deceive the system.
Do we maybe want to have a separate page on 51% attacks, and introduce that later, rather than touch on them briefly here? @michilumin ?

2021-12-21 22:53 UTC, MishaBoar commented on content/dogepedia/articles/what-is-a-blockchain.md
> +When a Dogecoin transaction is made, the information regarding the transaction is stored in what is a called a **block**, which is then distributed to the other nodes throughout the block**chain**. E
Hey Ross, thank you! I edited the suggestion to include your suggestions!

2021-12-21 23:11 UTC, Mishaboar2 commented on content/dogepedia/articles/what-is-a-blockchain.md
> +In addition to being peer-to-peer and decentralised, another benefit of blockchain technology is that is extremely difficult — and often impossible — to hack, alter, or deceive the system.
Yeah, maybe this is out of place here? @RichieJohn can completely ignore my suggestion!

2022-01-11 01:15 UTC, MishaBoar commented on content/dogepedia/articles/what-is-a-blockchain.md
> +In addition to being peer-to-peer and decentralised, another benefit of blockchain technology is that is extremely difficult — and often impossible — to hack, alter, or deceive the system.
@RichieJohn for this iteration, I think we can ignore this suggestion and use your version as per @rnicoll's suggestion. A separate article for 51% attacks will do.

2022-01-11 01:16 UTC, MishaBoar commented on content/dogepedia/articles/what-is-a-blockchain.md
> +When a Dogecoin transaction is made, the information regarding the transaction is stored in what is a called a **block**, which is then distributed to the other nodes throughout the block**chain**. E
Hey @RichieJohn - the suggested edits above include the changes Ross recommended.

2022-01-11 01:25 UTC, RichieJohn commented on content/dogepedia/articles/what-is-a-blockchain.md
> +In addition to being peer-to-peer and decentralised, another benefit of blockchain technology is that is extremely difficult — and often impossible — to hack, alter, or deceive the system.
OK - great. Thanks, @MishaBoar!

2022-01-11 03:23 UTC, MishaBoar approved these changes
Looks good to me!

2022-01-11 03:24 UTC, merged