'Dogecoin has no Utility' Article
dogecoinfoundation/dogecoin.com pull request #33
Opened 2021-12-21 06:02 UTC by RichieJohn

Super helpful outline provided by MishaBoar that I've made a few tweaks to. Please amend wherever you see fit.

2021-12-21 17:38 UTC, MishaBoar commented on content/dogepedia/faq/dogecoin-has-no-utility.md
> +Over the years, it became possible to use Dogecoin and spend it in online stores. The past 2 years have seen an explosion in the adoption, with Dogecoin payment integrations provided by third parties
```suggestion
Over the years, it became possible to use Dogecoin and spend it in online stores. The past 2 years have seen an explosion in the adoption, with Dogecoin payment integrations provided by third parties like BitPay and Coinbase and several providers providing prepaid cards supporting Dogecoin as a funding source. Shops can also integrate directly with the Dogecoin blockchain. The Dogecoin Foundation, alongside the ecosystem of developers, is planning to facilitate this further by creating libraries that will streamline and standardise implementations. 
```

2021-12-21 17:40 UTC, MishaBoar requested changes
Great, just added a tiny suggestion for clarity.

2021-12-21 17:40 UTC, MishaBoar commented on content/dogepedia/faq/dogecoin-has-no-utility.md
> +Over the years, it became possible to use Dogecoin and spend it in online stores. The past 2 years have seen an explosion in the adoption, with Dogecoin payment integrations provided by third parties
```suggestion
Over the years, it became possible to use Dogecoin and spend it in online stores. The past 2 years have seen an explosion in the adoption, with Dogecoin payment integrations provided by third parties like BitPay and Coinbase and several providers providing prepaid cards supporting Dogecoin as a funding source. Shops can also integrate directly with the Dogecoin blockchain. The Dogecoin Foundation, alongside the ecosystem of developers, is planning to facilitate this further by creating libraries that will streamline and standardise implementations.
```

2021-12-21 17:40 UTC, MishaBoar commented on content/dogepedia/faq/dogecoin-has-no-utility.md
> +Over the years, it became possible to use Dogecoin and spend it in online stores. The past 2 years have seen an explosion in the adoption, with Dogecoin payment integrations provided by third parties
Just edited for clarity in the end.

2021-12-22 06:09 UTC, RichieJohn commented on content/dogepedia/faq/dogecoin-has-no-utility.md
> +Over the years, it became possible to use Dogecoin and spend it in online stores. The past 2 years have seen an explosion in the adoption, with Dogecoin payment integrations provided by third parties
Much better. Thanks!

2022-01-11 01:18 UTC, MishaBoar approved these changes
Looks like I had missed your edits @RichieJohn, did not get any notification. Merging this!

2022-01-11 01:18 UTC, merged