'Dogecoin has No Developers' Article
dogecoinfoundation/dogecoin.com pull request #34
Opened 2021-12-21 06:28 UTC by RichieJohn

Link will need checking. Assuming that this will be the link for the Foundation website. As always, please edit wherever. Made a few tweaks - but still v much in line with original content.

2021-12-21 17:56 UTC, MishaBoar requested changes
Great! Just added some final linking to current repository, which we can always update on the fly later.

2021-12-21 17:56 UTC, MishaBoar commented on content/dogepedia/faq/dogecoin-has-no-developers.md
> +The Dogecoin Foundation’s [Trailmap](https://foundation.dogecoin.com/trailmap/) lists various projects as the ecosystem works towards its shared aim of becoming a currency for the People, by the Peop
```suggestion
The Dogecoin Foundation’s [Trailmap](https://foundation.dogecoin.com/trailmap/) lists various projects as the ecosystem works towards its shared aim of becoming a currency for the People, by the People! This Trailmap is not authoritative, but an indication of where to go that is open for community feedback.

Even though a lot of actual work is done outside of this repository, some of the development efforts can be followed on Github in the [**Dogecoin Core repository**](https://github.com/dogecoin/dogecoin). [**r/dogecoindev**](https://reddit.com/r/dogecoindev) on reddit is another good channel to discuss everything around Dogecoin's development and interact with the developers.
```

2022-01-11 03:06 UTC, MishaBoar requested changes

2022-01-11 03:06 UTC, MishaBoar commented on content/dogepedia/faq/dogecoin-has-no-developers.md
> +Dogecoin’s primary purpose has always been to be used as a currency, and since it was forked from Litecoin and then reforked from Bitcoin — with changed parameters to make it more suitable as a crypt
```suggestion
Dogecoin’s primary purpose has always been to be used as a currency. Dogecoin was originally a fork of a cryptocurrency called Luckycoin - itself a fork of Litecoin. Billy Markus, co-creator of Dogecoin with Jackson Palmer, acted as a solo developer for the first Dogecoin Core releases. In 2014, Billy and Jackson left Dogecoin development, and a new development team was formed.  Over the years, the Dogecoin development team has consisted of a small group of maintainers coordinating the work of more than 40 contributors.

In 2015, starting from Dogecoin Core 1.10.0, the Dogecoin development team decided to re-fork Dogecoin off Bitcoin, re-applying Litecoin changes on top of the Bitcoin codebase. Thus, throughout its history, Dogecoin inherited already feature-complete code bases, and it has shared a good part of its identity with Bitcoin. Its uniqueness came from changed parameters, optimizations, and parts of the code that were not inherited from Litecoin or Bitcoin. These changes were always aimed at making Dogecoin a viable currency for day to day spending, with a focus on utility and ease of use.
```

2022-01-11 03:06 UTC, MishaBoar commented on content/dogepedia/faq/dogecoin-has-no-developers.md
> +Dogecoin’s primary purpose has always been to be used as a currency, and since it was forked from Litecoin and then reforked from Bitcoin — with changed parameters to make it more suitable as a crypt
The original paragraph inherited from my stub contained some imprecise statements. I fixed it and expanded it in my suggestion.

2022-01-11 03:17 UTC, MishaBoar approved these changes

2022-01-11 03:17 UTC, merged

2022-01-11 03:18 UTC, RichieJohn reviewed
Looks good! This needs to be approved again before merging, I think, @MishaBoar :)

2022-01-11 03:18 UTC, RichieJohn commented
Oh - looks like it's automagically merged. :)

2022-01-11 03:19 UTC, RichieJohn commented
Ah - looks like it's already merged.